version: "3"

services:
  jupyterlab:
    build: compose/jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyterlab/data:/var/lib/foxstudios/neuroline/workspace/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
  label-studio:
    build: labelstudio
    ports:
      - "8080:8080"
    volumes:
      - ./mydata:/label-studio/data heartexlabs/label-studio:latest
